import { ROLES } from "./roles.js";

export const PERMISSIONS = {
  VIEW_DASHBOARD: [ROLES.VIEWER, ROLES.ANALYST, ROLES.ADMIN],
  VIEW_RECORDS: [ROLES.ANALYST, ROLES.ADMIN],
  CREATE_RECORD: [ROLES.ADMIN],
  UPDATE_RECORD: [ROLES.ADMIN],
  DELETE_RECORD: [ROLES.ADMIN],
  VIEW_INSIGHTS: [ROLES.ANALYST, ROLES.ADMIN],
  MANAGE_USERS: [ROLES.ADMIN],
};